name: PR job
on: [pull_request]

jobs:
  pr_job:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: master

      - name: Print branch
        run: ./.github/scripts/print_branch.sh

      - uses: actions/checkout@v2
        with:
          ref: 'test'

      - name: Print branch
        run: ./.github/scripts/print_branch.sh



      